import type { Product } from "@/entities/product";

// Временные данные-заглушки. Удалить, когда каталог начнет получать товары из /api/products.
export const PLACEHOLDER_PRODUCTS: (Product & { category_slug: string })[] = [
  {
    id: 1,
    category_id: 1,
    category_slug: "penoplast",
    slug: "ppt-25",
    name: "Пенопласт ППТ-25",
    description: "",
    price: 145,
    discount_price: null,
    price_unit: "руб/м³",
    is_volume_price: true,
    volume_price: { before_10: 150, from_10_to_20: 148, after_20: 145 },
    image_url: "/img/no_image.jpg",
    template: null,
    attributes: [],
    related_product_ids: [],
  },
  {
    id: 2,
    category_id: 2,
    category_slug: "xps",
    slug: "ecoplex-comfort",
    name: "Экструдированный пенополистирол Ecoplex",
    description: "",
    price: 210,
    discount_price: 195,
    price_unit: "руб/м³",
    is_volume_price: false,
    volume_price: null,
    image_url: "/img/no_image.jpg",
    template: null,
    attributes: [],
    related_product_ids: [],
  },
  {
    id: 3,
    category_id: 3,
    category_slug: "minvat-uteplitel",
    slug: "mineralnaya-vata-standart",
    name: "Минеральная вата, плита 50 мм",
    description: "",
    price: 168,
    discount_price: null,
    price_unit: "руб/м³",
    is_volume_price: false,
    volume_price: null,
    image_url: "/img/no_image.jpg",
    template: null,
    attributes: [],
    related_product_ids: [],
  },
  {
    id: 4,
    category_id: 4,
    category_slug: "smesi",
    slug: "kley-dlya-plitki-25kg",
    name: "Клей для плитки, 25 кг",
    description: "",
    price: 12,
    discount_price: null,
    price_unit: "руб/шт",
    is_volume_price: false,
    volume_price: null,
    image_url: "/img/no_image.jpg",
    template: null,
    attributes: [],
    related_product_ids: [],
  },
];
